#spring:
#  application:
#    name: NotesApp
#
#  datasource:
#    url: jdbc:h2:mem:notesdb
#    username: sa
#    password: 
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop # Tells Spring to build the tables automatically based on your Java Entities
#    show-sql: true
#    defer-datasource-initialization: true
#
#  h2:
#    console:
#      enabled: true 
#      path: /h2-console # You can view the database in your browser here
#
#  flyway:
#    enabled: false # Turn this off so it doesn't fight with H2


spring:
  application:
    name: NotesApp

  datasource:
    # Notice we swapped 5432 for 6543 to bypass the network block
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.gifpblcklivhwwbrbdfu&password=notesdb@pass190425
    
    username: postgres.gifpblcklivhwwbrbdfu
    
    # Don't forget to type your real database password here!
    password: notesdb@pass190425
    
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Set to 'update' so it safely creates the tables in the cloud
      ddl-auto: update 
    show-sql: true

  flyway:
    enabled: false